// Error codes for extension
#define FILEXT_SUCCESS 0
#define FILEXT_WRONG_ARG_COUNT 1
#define FILEXT_WRONG_FILE_NAME 2
#define FILEXT_WRONG_FUNCTION_NAME 3
#define FILEXT_FILE_NOT_OPEN 4
#define FILEXT_KEY_NOT_FOUND 5
#define FILEXT_KEY_NOT_FOUND 5
#define FILEXT_WRITE_ERROR 6
#define FILEXT_READ_ERROR 6
#define FILEXT_GET_MORE_AVAILABLE 7
#define FILEXT_WRONG_FILE_FORMAT 8