// Error codes for extension
#define FILEXT_SUCCESS 0
#define FILEXT_GET_MORE_AVAILABLE 1
#define FILEXT_ERROR_WRONG_ARG_COUNT 40
#define FILEXT_ERROR_WRONG_FILE_NAME 41
#define FILEXT_ERROR_WRONG_FUNCTION_NAME 42
#define FILEXT_ERROR_FILE_NOT_OPEN 43
#define FILEXT_ERROR_KEY_NOT_FOUND 44
#define FILEXT_ERROR_WRITE 45
#define FILEXT_ERROR_READ 46
#define FILEXT_ERROR_WRONG_FILE_FORMAT 47